# Generated by Django 5.2.5 on 2025-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_username', models.CharField(max_length=100)),
                ('user_count', models.CharField(max_length=150, unique=True)),
                ('user_comment', models.TextField()),
            ],
        ),
    ]
