# Generated by Django 5.2.8 on 2025-11-24 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='base_username',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.TextField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
