# Generated by Django 5.2.8 on 2025-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_base_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='base_username',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.TextField(max_length=32),
        ),
    ]
